#!/bin/bash

TARGET_DIRECTORY="certificate/"
CERTIFICATE_ARCHIVE_FILENAME="Test_Zertifikate.zip"

curl -sS -o "$TARGET_DIRECTORY$CERTIFICATE_ARCHIVE_FILENAME" https://download.elster.de/download/schnittstellen/"$CERTIFICATE_ARCHIVE_FILENAME" && \
unzip -j "$TARGET_DIRECTORY$CERTIFICATE_ARCHIVE_FILENAME" -d "$TARGET_DIRECTORY" test-softorg-pse.pfx && \
rm "$TARGET_DIRECTORY$CERTIFICATE_ARCHIVE_FILENAME"
